// Code generated by protoc-gen-go. DO NOT EDIT.
// source: templates/template.proto

package templates_pb // import "github.com/BadgeForce/sawtooth-utils/protos/templates_pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Template struct {
	Data                 *Data         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Verification         *Verification `protobuf:"bytes,2,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_e63a47ab17ade6f2, []int{0}
}
func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (dst *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(dst, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Template) GetVerification() *Verification {
	if m != nil {
		return m.Verification
	}
	return nil
}

type Data struct {
	IssuerPub            string          `protobuf:"bytes,1,opt,name=issuer_pub,json=issuerPub,proto3" json:"issuer_pub,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string          `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt            int64           `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Version              *Version        `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	CoreData             *_struct.Struct `protobuf:"bytes,7,opt,name=core_data,json=coreData,proto3" json:"core_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_e63a47ab17ade6f2, []int{1}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetIssuerPub() string {
	if m != nil {
		return m.IssuerPub
	}
	return ""
}

func (m *Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Data) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Data) GetCoreData() *_struct.Struct {
	if m != nil {
		return m.CoreData
	}
	return nil
}

type Version struct {
	Major                int32    `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                int32    `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch                int32    `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_e63a47ab17ade6f2, []int{2}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetMajor() int32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *Version) GetMinor() int32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *Version) GetPatch() int32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

type Verification struct {
	Signature            string   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	ProofOfIntegrityHash string   `protobuf:"bytes,2,opt,name=proof_of_integrity_hash,json=proofOfIntegrityHash,proto3" json:"proof_of_integrity_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Verification) Reset()         { *m = Verification{} }
func (m *Verification) String() string { return proto.CompactTextString(m) }
func (*Verification) ProtoMessage()    {}
func (*Verification) Descriptor() ([]byte, []int) {
	return fileDescriptor_template_e63a47ab17ade6f2, []int{3}
}
func (m *Verification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verification.Unmarshal(m, b)
}
func (m *Verification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verification.Marshal(b, m, deterministic)
}
func (dst *Verification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verification.Merge(dst, src)
}
func (m *Verification) XXX_Size() int {
	return xxx_messageInfo_Verification.Size(m)
}
func (m *Verification) XXX_DiscardUnknown() {
	xxx_messageInfo_Verification.DiscardUnknown(m)
}

var xxx_messageInfo_Verification proto.InternalMessageInfo

func (m *Verification) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Verification) GetProofOfIntegrityHash() string {
	if m != nil {
		return m.ProofOfIntegrityHash
	}
	return ""
}

func init() {
	proto.RegisterType((*Template)(nil), "template_pb.Template")
	proto.RegisterType((*Data)(nil), "template_pb.Data")
	proto.RegisterType((*Version)(nil), "template_pb.Version")
	proto.RegisterType((*Verification)(nil), "template_pb.Verification")
}

func init() { proto.RegisterFile("templates/template.proto", fileDescriptor_template_e63a47ab17ade6f2) }

var fileDescriptor_template_e63a47ab17ade6f2 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x65, 0xdc, 0x99, 0x9d, 0x4d, 0xcf, 0x5e, 0x6c, 0x06, 0x36, 0xca, 0x0a, 0xc3, 0x80, 0xb0,
	0x17, 0x13, 0xf0, 0x03, 0x44, 0xf0, 0xe0, 0x22, 0xa2, 0x78, 0x50, 0x5a, 0xf1, 0xe0, 0x25, 0x54,
	0x7a, 0x2a, 0x49, 0xcb, 0x4c, 0xba, 0xe9, 0xae, 0x5e, 0xd9, 0xff, 0xed, 0x0f, 0x90, 0xae, 0x4c,
	0x34, 0xbb, 0xb7, 0xae, 0xf7, 0x5e, 0xbd, 0xe2, 0x3d, 0x5a, 0xe4, 0x84, 0x07, 0xb7, 0x07, 0xc2,
	0x50, 0x8e, 0xaf, 0xc2, 0x79, 0x4b, 0x56, 0xae, 0xc6, 0xb9, 0x72, 0xf5, 0xe3, 0xcb, 0xd6, 0xda,
	0x76, 0x8f, 0x25, 0x53, 0x75, 0x6c, 0xca, 0x40, 0x3e, 0x6a, 0x1a, 0xa4, 0x5b, 0x27, 0xce, 0xbe,
	0x1f, 0xc5, 0xf2, 0xa9, 0x98, 0xef, 0x80, 0x20, 0x9f, 0x6d, 0x66, 0x57, 0xab, 0xe7, 0x0f, 0x8b,
	0x89, 0x4b, 0xf1, 0x1e, 0x08, 0x14, 0xd3, 0xf2, 0xad, 0x38, 0xbf, 0x41, 0x6f, 0x1a, 0xa3, 0x81,
	0x8c, 0xed, 0xf3, 0x07, 0x2c, 0x7f, 0x74, 0x47, 0xfe, 0x63, 0x22, 0x50, 0x77, 0xe4, 0xdb, 0x3f,
	0x33, 0x31, 0x4f, 0x6e, 0xf2, 0x89, 0x10, 0x26, 0x84, 0x88, 0xbe, 0x72, 0xb1, 0xe6, 0xa3, 0x99,
	0xca, 0x06, 0xe4, 0x6b, 0xac, 0xa5, 0x14, 0xf3, 0x1e, 0x0e, 0xc8, 0xf6, 0x99, 0xe2, 0xb7, 0xdc,
	0x88, 0xd5, 0x0e, 0x83, 0xf6, 0xc6, 0xf1, 0xe5, 0x13, 0xa6, 0xa6, 0x50, 0xda, 0xa2, 0x5b, 0x87,
	0xf9, 0x7c, 0xd8, 0x4a, 0xef, 0x74, 0x48, 0x7b, 0x04, 0xc2, 0x5d, 0x05, 0x94, 0x2f, 0x36, 0xb3,
	0xab, 0x13, 0x95, 0x1d, 0x91, 0x77, 0x24, 0x0b, 0xb1, 0xbc, 0x41, 0x1f, 0x92, 0xe1, 0x29, 0x47,
	0x59, 0xdf, 0x8f, 0x92, 0x38, 0x35, 0x8a, 0xe4, 0x4b, 0x91, 0x69, 0xeb, 0xb1, 0xe2, 0xae, 0x96,
	0xbc, 0x71, 0x51, 0x0c, 0x25, 0x17, 0x63, 0xc9, 0xc5, 0x37, 0x2e, 0x59, 0x9d, 0x25, 0x65, 0x4a,
	0xbb, 0xfd, 0x2c, 0x96, 0x47, 0x27, 0xb9, 0x16, 0x8b, 0x03, 0xfc, 0xb2, 0x9e, 0x33, 0x2f, 0xd4,
	0x30, 0x30, 0x6a, 0x7a, 0xeb, 0x39, 0x70, 0x42, 0xd3, 0x90, 0x50, 0x07, 0xa4, 0x3b, 0xce, 0xba,
	0x50, 0xc3, 0xb0, 0xd5, 0xe2, 0x7c, 0xda, 0xb0, 0xbc, 0x14, 0x59, 0x30, 0x6d, 0x0f, 0x14, 0x3d,
	0x8e, 0x4d, 0xfe, 0x03, 0xe4, 0x2b, 0x71, 0xe1, 0xbc, 0xb5, 0x4d, 0x65, 0x9b, 0xca, 0xf4, 0x84,
	0xad, 0x37, 0x74, 0x5b, 0x75, 0x10, 0xba, 0x63, 0xb9, 0x6b, 0xa6, 0xbf, 0x34, 0x9f, 0x46, 0xf2,
	0x23, 0x84, 0xee, 0xfa, 0xcd, 0xcf, 0xd7, 0xad, 0xa1, 0x2e, 0xd6, 0x85, 0xb6, 0x87, 0xf2, 0x1a,
	0x76, 0x2d, 0x7e, 0xb0, 0x5e, 0x63, 0x19, 0xe0, 0x37, 0x59, 0x4b, 0xdd, 0xb3, 0x48, 0x66, 0x1f,
	0x86, 0x8f, 0xf5, 0xff, 0x0f, 0x86, 0xca, 0xd5, 0xf5, 0x29, 0x83, 0x2f, 0xfe, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0xf6, 0x58, 0xbb, 0xa4, 0x02, 0x00, 0x00,
}
