// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credentials/payload.proto

package credentials_pb // import "github.com/BadgeForce/sawtooth-utils/protos/credentials_pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_ISSUE  Method = 0
	Method_REVOKE Method = 1
)

var Method_name = map[int32]string{
	0: "ISSUE",
	1: "REVOKE",
}
var Method_value = map[string]int32{
	"ISSUE":  0,
	"REVOKE": 1,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_payload_b4de367a6671454b, []int{0}
}

type RPCRequest struct {
	// Types that are valid to be assigned to Method:
	//	*RPCRequest_Issue
	//	*RPCRequest_Revoke
	Method               isRPCRequest_Method `protobuf_oneof:"method"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_payload_b4de367a6671454b, []int{0}
}
func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequest.Unmarshal(m, b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
}
func (dst *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(dst, src)
}
func (m *RPCRequest) XXX_Size() int {
	return xxx_messageInfo_RPCRequest.Size(m)
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

type isRPCRequest_Method interface {
	isRPCRequest_Method()
}

type RPCRequest_Issue struct {
	Issue *Issue `protobuf:"bytes,1,opt,name=issue,proto3,oneof"`
}

type RPCRequest_Revoke struct {
	Revoke *Revoke `protobuf:"bytes,2,opt,name=revoke,proto3,oneof"`
}

func (*RPCRequest_Issue) isRPCRequest_Method() {}

func (*RPCRequest_Revoke) isRPCRequest_Method() {}

func (m *RPCRequest) GetMethod() isRPCRequest_Method {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *RPCRequest) GetIssue() *Issue {
	if x, ok := m.GetMethod().(*RPCRequest_Issue); ok {
		return x.Issue
	}
	return nil
}

func (m *RPCRequest) GetRevoke() *Revoke {
	if x, ok := m.GetMethod().(*RPCRequest_Revoke); ok {
		return x.Revoke
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RPCRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RPCRequest_OneofMarshaler, _RPCRequest_OneofUnmarshaler, _RPCRequest_OneofSizer, []interface{}{
		(*RPCRequest_Issue)(nil),
		(*RPCRequest_Revoke)(nil),
	}
}

func _RPCRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RPCRequest)
	// method
	switch x := m.Method.(type) {
	case *RPCRequest_Issue:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Issue); err != nil {
			return err
		}
	case *RPCRequest_Revoke:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Revoke); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RPCRequest.Method has unexpected type %T", x)
	}
	return nil
}

func _RPCRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RPCRequest)
	switch tag {
	case 1: // method.issue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Issue)
		err := b.DecodeMessage(msg)
		m.Method = &RPCRequest_Issue{msg}
		return true, err
	case 2: // method.revoke
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Revoke)
		err := b.DecodeMessage(msg)
		m.Method = &RPCRequest_Revoke{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RPCRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RPCRequest)
	// method
	switch x := m.Method.(type) {
	case *RPCRequest_Issue:
		s := proto.Size(x.Issue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RPCRequest_Revoke:
		s := proto.Size(x.Revoke)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Issue struct {
	Params               *Credential `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	TemplateAddress      string      `protobuf:"bytes,2,opt,name=template_address,json=templateAddress,proto3" json:"template_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Issue) Reset()         { *m = Issue{} }
func (m *Issue) String() string { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()    {}
func (*Issue) Descriptor() ([]byte, []int) {
	return fileDescriptor_payload_b4de367a6671454b, []int{1}
}
func (m *Issue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issue.Unmarshal(m, b)
}
func (m *Issue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issue.Marshal(b, m, deterministic)
}
func (dst *Issue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issue.Merge(dst, src)
}
func (m *Issue) XXX_Size() int {
	return xxx_messageInfo_Issue.Size(m)
}
func (m *Issue) XXX_DiscardUnknown() {
	xxx_messageInfo_Issue.DiscardUnknown(m)
}

var xxx_messageInfo_Issue proto.InternalMessageInfo

func (m *Issue) GetParams() *Credential {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Issue) GetTemplateAddress() string {
	if m != nil {
		return m.TemplateAddress
	}
	return ""
}

type Revoke struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Revoke) Reset()         { *m = Revoke{} }
func (m *Revoke) String() string { return proto.CompactTextString(m) }
func (*Revoke) ProtoMessage()    {}
func (*Revoke) Descriptor() ([]byte, []int) {
	return fileDescriptor_payload_b4de367a6671454b, []int{2}
}
func (m *Revoke) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Revoke.Unmarshal(m, b)
}
func (m *Revoke) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Revoke.Marshal(b, m, deterministic)
}
func (dst *Revoke) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Revoke.Merge(dst, src)
}
func (m *Revoke) XXX_Size() int {
	return xxx_messageInfo_Revoke.Size(m)
}
func (m *Revoke) XXX_DiscardUnknown() {
	xxx_messageInfo_Revoke.DiscardUnknown(m)
}

var xxx_messageInfo_Revoke proto.InternalMessageInfo

func (m *Revoke) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "credential_pb.RPCRequest")
	proto.RegisterType((*Issue)(nil), "credential_pb.Issue")
	proto.RegisterType((*Revoke)(nil), "credential_pb.Revoke")
	proto.RegisterEnum("credential_pb.Method", Method_name, Method_value)
}

func init() { proto.RegisterFile("credentials/payload.proto", fileDescriptor_payload_b4de367a6671454b) }

var fileDescriptor_payload_b4de367a6671454b = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x37, 0x65, 0xc1, 0x3e, 0x11, 0x47, 0x50, 0xd8, 0x64, 0xa0, 0xec, 0x20, 0x53, 0xb4,
	0x45, 0xbd, 0x89, 0x17, 0x37, 0x26, 0x1b, 0x22, 0x4a, 0x86, 0x1e, 0xbc, 0x94, 0xb4, 0x79, 0xac,
	0xc5, 0xd6, 0xc4, 0x24, 0x55, 0xfc, 0xef, 0xa5, 0x69, 0xb5, 0x73, 0xb7, 0xe4, 0xfb, 0x7e, 0x7c,
	0xef, 0xe3, 0x3d, 0xe8, 0xc7, 0x1a, 0x05, 0xbe, 0xdb, 0x94, 0x67, 0x26, 0x50, 0xfc, 0x3b, 0x93,
	0x5c, 0xf8, 0x4a, 0x4b, 0x2b, 0xe9, 0x4e, 0x63, 0x85, 0x2a, 0x3a, 0x18, 0xac, 0x92, 0xcd, 0xbb,
	0x82, 0x87, 0x05, 0x00, 0x7b, 0x9a, 0x30, 0xfc, 0x28, 0xd0, 0x58, 0x7a, 0x06, 0x9d, 0xd4, 0x98,
	0x02, 0x7b, 0xed, 0xa3, 0xf6, 0x68, 0xfb, 0x72, 0xcf, 0xff, 0x17, 0xe5, 0xcf, 0x4b, 0x6f, 0xd6,
	0x62, 0x15, 0x44, 0x03, 0x20, 0x1a, 0x3f, 0xe5, 0x1b, 0xf6, 0x36, 0x1c, 0xbe, 0xbf, 0x86, 0x33,
	0x67, 0xce, 0x5a, 0xac, 0xc6, 0xc6, 0x5b, 0x40, 0x72, 0xb4, 0x89, 0x14, 0x43, 0x84, 0x8e, 0x0b,
	0xa3, 0x17, 0x40, 0x14, 0xd7, 0x3c, 0x37, 0xf5, 0xc8, 0xfe, 0x5a, 0xc6, 0xe4, 0xef, 0xc7, 0x6a,
	0x90, 0x9e, 0x40, 0xd7, 0x62, 0xae, 0x32, 0x6e, 0x31, 0xe4, 0x42, 0x68, 0x34, 0xc6, 0x15, 0xf0,
	0xd8, 0xee, 0xaf, 0x7e, 0x5b, 0xc9, 0xc3, 0x63, 0x20, 0x55, 0x09, 0x3a, 0x00, 0xaf, 0x66, 0xb1,
	0x1c, 0xb5, 0x39, 0xf2, 0x58, 0x23, 0x9c, 0x1e, 0x02, 0x79, 0x70, 0xc5, 0xa8, 0x07, 0x9d, 0xf9,
	0x62, 0xf1, 0x3c, 0xed, 0xb6, 0x28, 0x00, 0x61, 0xd3, 0x97, 0xc7, 0xfb, 0x69, 0xb7, 0x3d, 0xbe,
	0x79, 0xbd, 0x5e, 0xa6, 0x36, 0x29, 0x22, 0x3f, 0x96, 0x79, 0x30, 0xe6, 0x62, 0x89, 0x77, 0x52,
	0xc7, 0x18, 0x18, 0xfe, 0x65, 0xa5, 0xb4, 0xc9, 0x79, 0x61, 0xd3, 0xf2, 0x12, 0xe5, 0x52, 0x57,
	0xd7, 0x6c, 0x42, 0x15, 0x45, 0xc4, 0xc9, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x0f,
	0xcd, 0x65, 0xb5, 0x01, 0x00, 0x00,
}
